import { DisposableAction, DisposableContainer, type IDisposable } from "../src"

describe("container", () => {
  it("should be disposed", () => {
    const container = new DisposableContainer()
    expect(container.disposed).toBe(false)
    container.dispose()
    expect(container.disposed).toBe(true)
  })
  it("should set disposable", () => {
    const container = new DisposableContainer()
    const action = jest.fn()
    container.set(new DisposableAction(action))
    expect(action).toHaveBeenCalledTimes(0)
    container.dispose()
    expect(action).toHaveBeenCalledTimes(1)
    container.set(new DisposableAction(action))
    expect(action).toHaveBeenCalledTimes(2)
    container.dispose()
    expect(action).toHaveBeenCalledTimes(2)
  })
  it("should set null disposable and not fail if already disposed", () => {
    const container = new DisposableContainer()
    container.dispose()
    container.set(null)
  })

  it("should set undefined disposable and not fail if already disposed", () => {
    const container = new DisposableContainer()
    container.dispose()
    container.set(undefined)
  })
  it("should replace disposable", () => {
    const container = new DisposableContainer()
    const action = jest.fn()
    container.set(new DisposableAction(action))
    expect(action).toHaveBeenCalledTimes(0)
    container.replace(new DisposableAction(action))
    expect(action).toHaveBeenCalledTimes(0)
    container.dispose()
    expect(action).toHaveBeenCalledTimes(1)
    container.replace(new DisposableAction(action))
    expect(action).toHaveBeenCalledTimes(2)
  })
  it("should replace null disposable and not fail if already disposed", () => {
    const container = new DisposableContainer()
    container.dispose()
    container.replace(null)
  })
  it("should replace undefined disposable and not fail if already disposed", () => {
    const container = new DisposableContainer()
    container.dispose()
    container.replace(undefined)
  })
  it("should return last disposable", () => {
    const container = new DisposableContainer()
    expect(container.disposable).toBeUndefined()
    const disposable = new DisposableAction(() => {})
    container.set(disposable)
    expect(container.disposable).toBe(disposable)
    const disposable2 = new DisposableAction(() => {})
    container.replace(disposable2)
    expect(container.disposable).toBe(disposable2)
    container.replace(disposable)
    expect(container.disposable).toBe(disposable)
    container.dispose()
    expect(container.disposable).toBeUndefined()
  })
  it("should set dispose current disposable", () => {
    const container = new DisposableContainer()
    const action = jest.fn()
    container.set(new DisposableAction(action))
    expect(action).toHaveBeenCalledTimes(0)
    container.set(new DisposableAction(action))
    expect(action).toHaveBeenCalledTimes(1)
    container.dispose()
    expect(action).toHaveBeenCalledTimes(2)
    container.set(new DisposableAction(action))
    expect(action).toHaveBeenCalledTimes(3)
    container.dispose()
    expect(action).toHaveBeenCalledTimes(3)
  })
  it("can use global Disposable API", () => {
    const action = jest.fn()
    {
      using _ = new DisposableContainer(new DisposableAction(action))
      expect(action).toHaveBeenCalledTimes(0)
    }
    expect(action).toHaveBeenCalledTimes(1)
  })
  it("should dispose only current disposable", () => {
    const container = new DisposableContainer()
    const fun = jest.fn()
    container.set(new DisposableAction(fun))
    container.disposeCurrent()
    expect(fun).toHaveBeenCalledTimes(1)
    container.set(new DisposableAction(fun))
    expect(fun).toHaveBeenCalledTimes(1)
    container.dispose()
    expect(fun).toHaveBeenCalledTimes(2)
  })
  it("should not fail on disposeCurrent if no disposable", () => {
    const container = new DisposableContainer()
    container.disposeCurrent()
    container.dispose()
  })
  it("set should not fail on null", () => {
    const container = new DisposableContainer()
    container.set(null as IDisposable)
    container.dispose()
  })
  it("replace should not fail on null", () => {
    const container = new DisposableContainer()
    container.replace(null as IDisposable)
    container.dispose()
  })
})
